# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cad88690647ad448299f506fbd03d4a31c3d1f12d9172415f4893155ad389c00b6783f0ea331b4ea48effb87778de9c57aafa736a54666419f7388a088e52645

test:
  secret_key_base: ec427a76c0a87d9bec351d193e83371c6f6453b792421bb65a0723eecc935983f71b4c317eb7553f023cd1cf7f0e8b8d835d7f554acb9e9dc8c66d403bbd2d06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
